spring.application.name=food-delivery-01
server.port=8081
spring.profiles.active=prod
# Actuator & Prometheus Metrics Configuration
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true


# ==============================================================================
# Logging Configuration
# ==============================================================================
# Explicitly enable INFO logging for your application code package
logging.level.com.ait.app=INFO
logging.level.org.hibernate.SQL=INFO
#
# Set format_sql to false so multi-line SQL queries don't break Loki/Grafana log parsing
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false