package com.ait.app.enums;

public enum FoodCategory {
	BREAKFAST, STARTER, MAIN_COURSE, RICE, BHAJI, BHAKRI, ROTI, THALI, SNACKS, STREET_FOOD, FAST_FOOD, MISAL, VADA_PAV,
	PAV_BHAJI, SOUTH_INDIAN, CHINESE, DESSERT, SWEETS, BEVERAGES
}